services:
  - type: web
    name: assistente-co2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend_assistente_co2:app --host 0.0.0.0 --port 10000
    envVars:
      - key: API_KEY
        value: co2-4Zx8tA91K3rQp72N
