services:
  - type: web
    name: assistente-co2
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend_assistente_co2:app --host 0.0.0.0 --port 10000
    envVars:
      - key: API_KEY
        value: SUA_CHAVE_PRIVADA
    autoDeploy: true
